backend:
  name: git-gateway
  branch: master
  open_authoring: true

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "Open Workshop"
    label: "Open Workshop"
    folder: "content/workshops"
    description: "Workshop date, description, and links to class content."
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - { label: "Privacy Setting", name: "privacySetting", widget: "hidden", default: "open" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: Thumbnail, name: thumbnail, widget: image}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Readings", 
          name: "readings", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: File, name: file, required: false, widget: file},
            { label: URL, name: url, required: false, widget: string}
          ]}
      - { label: "Lectures", 
          name: "lectures", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: File, name: file, required: false, widget: file},
            { label: URL, name: url, required: false, widget: string}
          ]}
      - { label: "Links", 
          name: "links", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: File, name: file, required: false, widget: file},
            { label: URL, name: url, required: false, widget: string}
          ]}
      - { label: "Gallery Images", 
          name: "gallery image", 
          widget: "list", 
          fields: [
            { label: Image, name: image, required: true, widget: image },
            { label: Alt Text, name: alt text, required: true, widget: string}
          ]}
  - name: "Private Workshop"
    label: "Private Workshop"
    folder: "content/privateWorkshops"
    description: "Private workshop date, description, and links to class content."
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: Thumbnail, name: thumbnail, widget: image}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Readings", 
          name: "readings", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: File, name: file, widget: file },
            { label: URL, name: url, widget: string}
          ]}
      - { label: "Lectures", 
          name: "lectures", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: File, name: file, required: true, widget: file },
            { label: URL, name: url, widget: string}
          ]}
      - { label: "Links", 
          name: "links", 
          widget: "list", 
          fields: [
            { label: Name, name: name, required: true, widget: string },
            { label: URL, name: url, widget: string}
          ]}
      - { label: "Gallery Images", 
          name: "gallery image", 
          widget: "list", 
          fields: [
            { label: Image, name: image, required: true, widget: image },
            { label: Alt Text, name: alt text, widget: string}
          ]}
  - name: "Extra Reading"
    label: "Extra Reading"
    folder: "content/extraReadings"
    description: "Any readings above and beyond those listed in the public workshops."
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields: 
      - { label: "Title", name: "title", required: true, widget: "string" }
      - { label: "File", name: "file", widget: "file" }
      - { label: "URL", name: "url", widget: "string"}
  - name: "Extra Lectures"
    label: "Extra Lectures"
    folder: "content/extraLectures"
    description: "Any readings above and beyond those listed in the public workshops."
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields: 
      - { label: "Title", name: "title", required: true, widget: "string" }
      - { label: "File", name: "file", widget: "file" }
      - { label: "URL", name: "url", widget: "string"}
  - name: "Extra Links"
    label: "Extra Links"
    folder: "content/extraLinks"
    description: "Any links above and beyond those listed in the public workshops."
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields: 
      - { label: "Title", name: "title", required: true, widget: "string" }
      - { label: "File", name: "file", widget: "file" }
      - { label: "URL", name: "url", widget: "string"}
  - name: "Extra Gallery Images"
    label: "Extra Links"
    folder: "content/extraGalleryImages"
    description: "Any image above and beyond those included in the public workshops."
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields: 
      - { label: "Image", name: "image", required: true, widget: "image" }
      - { label: "Alt Text", name: "alt text", widget: "string" }

